version: '3.8'
services:
  #ngix
  web:
    build:
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  
  #php
  app:
    build:
      dockerfile: ./php/Dockerfile
      target: app
  
  #mysql
  db:
    image: mysql
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: docker-php
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret

  #adminer
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  #redis

volumes:
  mysqldata:
